// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwakm0lhzm3CDKtzkcV44Zg2VgKcCXT8',
    appId: '1:1046095587693:web:848cd6c2566182944b1264',
    messagingSenderId: '1046095587693',
    projectId: 'devoida-task',
    authDomain: 'devoida-task.firebaseapp.com',
    storageBucket: 'devoida-task.firebasestorage.app',
    measurementId: 'G-Y5KB45C464',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4lxE-stGlvRLcfGtxrXCQaOmCbeIrXXM',
    appId: '1:1046095587693:android:75dd910005e2e7274b1264',
    messagingSenderId: '1046095587693',
    projectId: 'devoida-task',
    storageBucket: 'devoida-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgtHxwOjQ_CbyOhjdEO5K51cCPALWblps',
    appId: '1:1046095587693:ios:da74e937943e03014b1264',
    messagingSenderId: '1046095587693',
    projectId: 'devoida-task',
    storageBucket: 'devoida-task.firebasestorage.app',
    iosBundleId: 'com.example.devoidaTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgtHxwOjQ_CbyOhjdEO5K51cCPALWblps',
    appId: '1:1046095587693:ios:da74e937943e03014b1264',
    messagingSenderId: '1046095587693',
    projectId: 'devoida-task',
    storageBucket: 'devoida-task.firebasestorage.app',
    iosBundleId: 'com.example.devoidaTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQwakm0lhzm3CDKtzkcV44Zg2VgKcCXT8',
    appId: '1:1046095587693:web:4825f26a5f5300054b1264',
    messagingSenderId: '1046095587693',
    projectId: 'devoida-task',
    authDomain: 'devoida-task.firebaseapp.com',
    storageBucket: 'devoida-task.firebasestorage.app',
    measurementId: 'G-X6KBFSD1RM',
  );
}
